runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: DB-USERNAME
  CLOUD_SQL_PASSWORD: DB-PASSWORD
  CLOUD_SQL_DATABASE_NAME: DB-NAME
  CLOUD_SQL_CONNECTION_NAME: CONN-NAME
# [END gae_python37_cloudsql_config]